name: Simple Deployment Pipeline

on:
  push:
    branches: 
      - main

jobs: 
  checkout_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

  deployment_job:
    needs: checkout_job
    runs-on: ubuntu-20.04
    steps:
      - run: | 
          echo "DESTROY AND DOMINATE"

