name: Simple Deployment Pipeline

on:
  push:
    branches: 
      - main

jobs: 
  checkout_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - run: |
          pwd 
          ls -la
      - name: Install dependencies
        run: npm install
      # - name: Linting
      #   run: npm run eslint

      - name: Test Info
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: info
            details: Test succeeded.
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Warn
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: warn
            details: Test warning.
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Error
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: error
            details: Test error.
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  # deployment_job:
  #   needs: checkout_job
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - run: | 
  #         echo "DESTROY AND DOMINATE"
  #
