name: Running Script file in Runner! 

on: 
  push:
    branches: 
      - dev

jobs: 
  running_script_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Saving Script
        run: |
            echo "console.log('hello there')" > script.js
            ls -la
            chmod +x script.js
      - name: Running Script file
        run: |
            ls -la
            node -v 
            node script.js
  fun_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Speedtest
        run: |
            sudo apt install curl
            ls -la ~/
            curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -
